/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const DashboardCompanyIdIndexLazyRouteImport = createFileRoute(
  '/dashboard/$companyId/',
)()
const DashboardCompanyIdActionsIndexLazyRouteImport = createFileRoute(
  '/dashboard/$companyId/actions/',
)()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCompanyIdIndexLazyRoute =
  DashboardCompanyIdIndexLazyRouteImport.update({
    id: '/dashboard/$companyId/',
    path: '/dashboard/$companyId/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/dashboard/$companyId/index.lazy').then((d) => d.Route),
  )
const DashboardCompanyIdActionsIndexLazyRoute =
  DashboardCompanyIdActionsIndexLazyRouteImport.update({
    id: '/dashboard/$companyId/actions/',
    path: '/dashboard/$companyId/actions/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/dashboard/$companyId/actions/index.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/$companyId/': typeof DashboardCompanyIdIndexLazyRoute
  '/dashboard/$companyId/actions/': typeof DashboardCompanyIdActionsIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/$companyId': typeof DashboardCompanyIdIndexLazyRoute
  '/dashboard/$companyId/actions': typeof DashboardCompanyIdActionsIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/$companyId/': typeof DashboardCompanyIdIndexLazyRoute
  '/dashboard/$companyId/actions/': typeof DashboardCompanyIdActionsIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard/$companyId/' | '/dashboard/$companyId/actions/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard/$companyId' | '/dashboard/$companyId/actions'
  id:
    | '__root__'
    | '/'
    | '/dashboard/$companyId/'
    | '/dashboard/$companyId/actions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardCompanyIdIndexLazyRoute: typeof DashboardCompanyIdIndexLazyRoute
  DashboardCompanyIdActionsIndexLazyRoute: typeof DashboardCompanyIdActionsIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$companyId/': {
      id: '/dashboard/$companyId/'
      path: '/dashboard/$companyId'
      fullPath: '/dashboard/$companyId/'
      preLoaderRoute: typeof DashboardCompanyIdIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$companyId/actions/': {
      id: '/dashboard/$companyId/actions/'
      path: '/dashboard/$companyId/actions'
      fullPath: '/dashboard/$companyId/actions/'
      preLoaderRoute: typeof DashboardCompanyIdActionsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardCompanyIdIndexLazyRoute: DashboardCompanyIdIndexLazyRoute,
  DashboardCompanyIdActionsIndexLazyRoute:
    DashboardCompanyIdActionsIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
